services:
    _defaults:
        public: true
        autowire: false

    HBM\BootstrapFormBundle\Form\Extension\:
        resource: '../../Form/Extension'
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
